name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: [ main ] # Ejecutar cada vez que subas cambios a la rama main

# Otorgar permisos al token de GitHub para publicar en Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permitir solo un despliegue simultáneo
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # 1. Obtener el código fuente del repositorio
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Configurar el entorno de .NET
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x' # Cambia a '9.0.x' si usas .NET 9

      # 3. Compilar y publicar el proyecto en modo Release
      - name: Publish Blazor App
        run: dotnet publish quinielas/quinielas.csproj -c Release -o release

      # 4. (Diagnóstico) Ver qué archivos se generaron en la carpeta release
      - name: List generated files
        run: ls -R release

      # 5. Agregar archivo .nojekyll (Evita que GitHub ignore carpetas que inician con _)
      - name: Add .nojekyll file
        run: |
          touch release/wwwroot/.nojekyll
          touch release/.nojekyll

      # 6. Cambiar la etiqueta <base href="/" /> para que coincida con la URL del repositorio
      # GitHub Pages aloja sitios en https://usuario.github.io/nombre-repo/
      - name: Change base-tag in index.html
        run: |
          sed -i 's/<base href="\/" \/>/<base href="\/${{ github.event.repository.name }}\/" \/>/g' release/wwwroot/index.html
          sed -i 's/<base href="\/" \/>/<base href="\/${{ github.event.repository.name }}\/" \/>/g' release/wwwroot/404.html


      # 7. Cargar los archivos estáticos generados
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'release/wwwroot'

      # 8. Desplegar los archivos en GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4